### ISSUE TITLE
Generate more clean HTML with command line tool

### ISSUE THREAD

**Issue by sgtpep** [ojjs/oj#3]
Command line tool embeds inline a lot of styles and scripts (especially scripts). Perhaps it does not matter in case of single page applications, but with more than one page it brings redundancy.

May be it is possible to automatically split generated code into separate .css, .js and .html (which includes them).

I think that OJ has a potential to be more universal tool than just a view component for client-side applications. It could be, for example, very elegant static site generator which requires you to write only one concise .oj/.ojs per page, instead of dealing with separate verbose .html, .css and .js files.

**Comment by evanmoran** [comment]
This is now done. OJ commandline now supports more general outputing capabilities. See the full options list by running the commandline
